### ISSUE TITLE
Slack 'test configuration' works fine but doesn't notify on new event

### ISSUE THREAD

**Issue by will3942** [getsentry/sentry-slack#17] opened 2015-07-20 17:05 UTC
Doesn't notify on a new event but test configuration works. No errors in Sentry logs unless this is related:

`Ignored empty interface value: user`

**Comment by mlaitinen** [comment] 2015-07-23 14:23
Are you sure the Slack integration is currently enabled? I'm asking because the integration page is a bit confusing. Here's what I did:
 1. I enabled Slack integration (note: I didn't click "Save changes")
 1. I clicked on the Slack link and got to the configuration page
 1. I entered the webhook URL and the test worked fine. I saved changes.
 1. I went back to the integration page -> Slack was **not** enabled.

It wasn't enabled because after the first step I didn't click on "Save changes". So I enabled it and saved changes and everything went smooth after that. 

If it's not that, you could check your notification settings.

**Comment by will3942** [comment] 2015-07-23 14:51
Not working, I've done all of that.
![screen shot 2015-07-23 at 15 50 31](https://cloud.githubusercontent.com/assets/1151860/8853462/b4c7f5b4-3152-11e5-9844-4e20574b8f8d.png)
![screen shot 2015-07-23 at 15 50 56](https://cloud.githubusercontent.com/assets/1151860/8853463/b4cc63b0-3152-11e5-81a2-9c5b314c8535.png)
![screen shot 2015-07-23 at 15 51 08](https://cloud.githubusercontent.com/assets/1151860/8853464/b4d73862-3152-11e5-8ca2-e22f676b2e8e.png)
![screen shot 2015-07-23 at 15 51 22](https://cloud.githubusercontent.com/assets/1151860/8853465/b4e6b3aa-3152-11e5-8db0-912cac4ed56a.png)

**Comment by Surgo** [comment] 2015-07-30 01:34
Not working on app.getsentry.com too.

**Comment by kyriog** [comment] 2015-07-30 08:18
Confirmed here using Sentry 7.6.2 and Slack module 0.2.0.
Slack checkbox is checked in integration page.
Using my forked [Magento Sentry extension](https://github.com/kyriog/magento-amg-sentry-extension).
I even tried to set a specific action "Send a notification via Slack" for new event and regression rules, but still nothing on Slack.

"Test settings" button works great.

**Comment by syymza** [comment] 2015-08-03 11:59
Not working here too.

**Comment by willemwy** [comment] 2015-08-13 10:46
Can confirm too

**Comment by d3chapma** [comment] 2015-08-14 14:16
This has been an issue for a while for us to. Has anyone gotten things working?

**Comment by willemwy** [comment] 2015-08-14 14:37
I actually fixed mine, firstly I didn't use the Slack Sentry integration and instead used the incoming-webhook one. I also saw that all my notifications rules were off. Hopefully that helps a few people.

**Comment by dcramer** [comment] 2015-08-14 17:37
This is certainly resolved on getsentry.com, with the latest Sentry versions, and the latest version of the Slack repo.

That said we don't aggressively do point releases, so you'd need to install the version from Git (i.e. pip install <url to tarball>)

**Comment by chris-erickson** [comment] 2015-09-09 15:34
I updated to the most current commit to master, and now the test doesn't work either.  I get another exception inside ```sentry-slack```:

```
New Event on Sentry Backend

Plugin(slack) raised an error during test
```

```
AttributeError: 'Project' object has no attribute 'get_full_name'
  File "sentry/web/helpers.py", line 170, in plugin_config
    test_results = plugin.test_configuration(project)
  File "sentry/plugins/bases/notify.py", line 115, in test_configuration
    return self.notify(notification)
  File "sentry_slack/plugin.py", line 101, in notify
    project_name = project.get_full_name().encode('utf-8')
```

What's going on?  Really want to get this working since we are looking to use Slack more.

**Comment by mattrobenolt** [comment] 2015-09-10 06:50
Try again with 0.3.0, and if this is still an issue, plz reopen and I'll take a look. :)

**Closed by mattrobenolt** 2015-09-10 06:50 UTC

**Comment by ebsaral** [comment] 2016-03-03 14:05
sentry==8.0.1
sentry-slack==0.4.0

Having the same problem. Test notification gets delivered but events don't. Any idea why?

**Comment by andhikamaheva** [comment] 2017-09-05 05:28
Not working with me too :cry:

**Comment by AdrianAntunez** [comment] 2018-01-04 09:50
not working for me either

**Comment by newbreedofgeek** [comment] 2023-04-17 10:25
Had the same issue but fixed it.

- Setup the incoming webhook
- Setup the integration on Slack. Made sure everything was "saves and turned on"
- The "test configuration" worked fine, but actual issue did not go to Slack
- RESOLVED by : Each sentry project now has "Alerts" and you need to now configure the Alerts of the project to "send a notification to integrations" (by default it does not have this selected). After doing this, the actual issues were sent to Slack. But remember that it only sends NEW issue alerts by default (so if you resolve an issue and it appears again then the alert wont come).. you need to fine tune your Alerts to get everything to appear in Slack
